Split into separate endpoints
BogdanParashchak/GoodsPartner pull request #10
Opened 2022-07-08 08:43 UTC by BogdanParashchak

Existing endpoint splitted into 3 different endpoints
'/calculate/addresses' endpoint replaced with '/calculate/routes' which returns mock DTO

2022-07-08 08:46 UTC, Rooman requested changes

2022-07-08 08:46 UTC, Rooman commented on src/main/resources/application.properties
> -spring.datasource.url=${JDBC_DATABASE_URL}
хорошая практика смотреть на свой пул реквест до того как его публиковать ;)

2022-07-08 08:46 UTC, Rooman commented on src/main/java/com/goods/partner/entity/Route.java
> +@Setter
@Data

2022-07-08 08:46 UTC, Rooman commented on src/main/java/com/goods/partner/dto/RouteDto.java
> +@Data
убери геттер и сеттер потому что дата стоит

2022-07-08 19:44 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/entity/Route.java
> +@Setter
Looks like @Data is not recomended to be used (see below)
![image](https://user-images.githubusercontent.com/86907923/178060014-f5fa4fb3-99ea-433a-8f37-446a82db2028.png)

2022-07-08 20:43 UTC, 0ffffh requested changes

2022-07-08 20:43 UTC, 0ffffh commented on src/main/java/com/goods/partner/dto/RouteDto.java
> +@Data
remove @Data

2022-07-08 20:58 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/dto/RouteDto.java
> +@Data
https://github.com/BogdanParashchak/GoodsPartner/pull/10#discussion_r917095924

2022-07-08 21:03 UTC, Rooman commented on src/main/java/com/goods/partner/entity/Route.java
> +@Setter
Резонно

2022-07-08 21:04 UTC, Rooman commented on src/main/java/com/goods/partner/dto/RouteDto.java
> +@Data
ну а в чем он не прав?)

2022-07-09 19:53 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/dto/RouteDto.java
> +@Data
Кос правий, @Data приберу

2022-07-10 22:04 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/dto/RouteDto.java
> +@Data
Done

2022-07-12 20:21 UTC, closed without merging