add_information_about_total_weight_for_all_orders (backend part)
BogdanParashchak/GoodsPartner pull request #102
Opened 2022-08-19 12:54 UTC by Eugene7011

backend part

2022-08-19 13:04 UTC, 0ffffh reviewed
Насколько я понял, нужен вес не всех ордеров, а только тех что загружены в автомобили?

2022-08-19 13:57 UTC, belosh59 commented
> Collaborator

Наоборот нужен именно вес все ордеров которые мы выгрузили.

Таким образом сразу прослеживается разница между весом выгруженных ордеров и заполнением машин

2022-08-19 13:58 UTC, belosh59 approved these changes

2022-08-19 13:59 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultOrderService.java
> +                .mapToDouble(OrderDto::getOrderWeight)
D0 we really need double here?

2022-08-19 22:50 UTC, Rooman requested changes
добавляется логика, добавляются поля. 
Тестов 0 на это.

2022-08-21 14:45 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultOrderService.java
> +                .mapToDouble(OrderDto::getOrderWeight)
У нас же вес везде используется как дабл. Не уловил суть

2022-08-23 20:28 UTC, BogdanParashchak reviewed
Please ASAP contact Nastya to approve OrdersCalculation

2022-08-23 20:51 UTC, belosh59 commented
So we still return double? I would suggest either to go with long on BE side or at least strip the precision on to 2 digits after dot

2022-08-24 01:14 UTC, Rooman commented
@belosh59 As discussed on scrum we will leave double and format it on UI.

2022-08-24 01:14 UTC, Rooman approved these changes

2022-08-24 08:04 UTC, NastyaBondarenko approved these changes

2022-08-24 08:24 UTC, merged