Migrate to WebClient
BogdanParashchak/GoodsPartner pull request #105
Opened 2022-08-23 07:53 UTC by Ishei5

- added custom deserializers;
- added URL1CBuilder

2022-08-23 20:43 UTC, BogdanParashchak reviewed
When are you going to add refKey to OrderDto? in this or another PR?

2022-08-23 20:43 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/WebClientTest.java
> +//        assertEquals(ORDER_FETCH_LIMIT, block.getNodeType());
is it nessesary here?

2022-08-23 20:49 UTC, belosh59 commented on goods-partner-backend/src/test/java/com/goodspartner/service/WebClientTest.java
> +//        assertEquals(ORDER_FETCH_LIMIT, block.getNodeType());
It is a draft so far.

Illa need to add additional chnges

2022-08-24 15:29 UTC, Rooman requested changes

2022-08-24 15:29 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderMapper.java
> +    public OrderDto toOrderDto(ODataOrderDto oDataOrderDto) {
с каких пор у нас паблик это модификатор для тестов?

2022-08-24 15:29 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderMapper.java
> +    public OrderDto toOrderDto(ODataOrderDto oDataOrderDto) {
замени на мап стракт

2022-08-24 15:29 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/ProductMapper.java
> +    @Mapping(target = "storeName", source = "storeName", qualifiedByName = "getStoreName")
нужно ли прописывать аннотацию маппинг если таргет и сорс одинаковые?

2022-08-24 15:29 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/ProductMapper.java
> +    double getTotalWeight(ODataProductDto oDataProductDto) {
Меня смущает этот метод. В моем понимании маппер, исключеительно перемапливает на ДТО. А у нас тут калькуляции по переводу. 
Как минимум поставь тудушку что это нужно вынести.

2022-08-24 15:29 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/GrandeDolceOrderService.java
> +    public static final String SERVER_ODATA_URL = "http://89.76.239.245:8080/test/odata/standard.odata/";
Хост в пропертя

2022-08-24 15:29 UTC, Rooman commented on goods-partner-backend/src/test/java/com/goodspartner/service/WebClientTest.java
> +public class WebClientTest extends AbstractBaseITest {
Зачем тебе тут спринг? Почему это не юнит тест?

2022-08-24 19:11 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/ProductMapper.java
> +    @Mapping(target = "storeName", source = "storeName", qualifiedByName = "getStoreName")
если не использовать для этих полей доп логику для обработки, то не нужно, а иначе вроде qualifier не навешать

2022-08-24 19:40 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/GrandeDolceOrderService.java
> +    public static final String SERVER_ODATA_URL = "http://89.76.239.245:8080/test/odata/standard.odata/";
Принято

2022-08-25 09:49 UTC, belosh59 commented
Нужно фиксануть конфликты с мастером

2022-08-25 18:05 UTC, belosh59 commented on goods-partner-backend/src/test/java/com/goodspartner/service/WebClientTest.java
> +    private WebClient webClient;
@Rooman  вот для этого нужен спринг

@0ffffh мы тут потом переиспользуем твой солюшен с моковыми данными для Webclient

2022-08-25 18:05 UTC, belosh59 approved these changes

2022-08-25 19:31 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderMapper.java
> +    public OrderDto toOrderDto(ODataOrderDto oDataOrderDto) {
Принято

2022-08-25 19:35 UTC, BogdanParashchak commented on goods-partner-backend/src/main/resources/application.yml
> +    url: http://89.76.239.245:8080/test/odata/standard.odata/
це схоже на непублічну інформацію
може краще перемістимо в application-dev.yml ?

2022-08-25 19:37 UTC, Rooman commented on goods-partner-backend/src/test/java/com/goodspartner/service/WebClientTest.java
> +    private WebClient webClient;
@belosh59 Чтобы в тест закинуть инстанс класса?

2022-08-25 20:49 UTC, belosh59 commented on goods-partner-backend/src/main/resources/application.yml
> +    url: http://89.76.239.245:8080/test/odata/standard.odata/
ми можемо запускати сервіс із env-variable так як ми це робимо для GoogleApiKey etc

2022-08-25 20:50 UTC, belosh59 commented on goods-partner-backend/src/main/resources/application.yml
> +    url: http://89.76.239.245:8080/test/odata/standard.odata/
```
google:
  api:
    key: ${GOOGLE_API_KEY}
```

2022-08-25 21:13 UTC, belosh59 commented on goods-partner-backend/src/test/java/com/goodspartner/service/WebClientTest.java
> +public class WebClientTest extends AbstractBaseITest {
Я думаю этот тест мы вприниципе могли бы удалить.
Он использовался в процессе девелопмента что бы понять как правильно маппится json возвращаемый от 1С на обьект. Я думаю нам нету толку с этого теста anymore. Разве что мы будем создавать и кастомизировать Webclient на моковый ответ

2022-08-25 22:13 UTC, Ishei5 commented on goods-partner-backend/src/main/resources/application.yml
> +    url: http://89.76.239.245:8080/test/odata/standard.odata/
отредактировал

2022-08-26 04:05 UTC, Rooman approved these changes

2022-08-26 07:36 UTC, merged