62-get-and-process-orders
BogdanParashchak/GoodsPartner pull request #106
Opened 2022-08-23 17:58 UTC by NastyaBondarenko

use MockOrderAddressValidator for validate address

2022-08-23 19:04 UTC, Rooman requested changes

2022-08-23 19:04 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderExternalMapper.java
> +@Component
map struct

2022-08-23 19:04 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/entity/OrderExternal.java
> +    @Type(type = "json")
почему тут тип json?

2022-08-23 19:04 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/validator/MockOrderAddressValidator.java
> +@Component
service

2022-08-23 19:04 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/OrderController.java
> +        List<OrderDto> validOrders = mockOrderAddressValidator.getValidOrders(ordersByDate);
тут нужен рефакторинг. Почему в контроллере тоже моковый код? 
Нужно чтобы был сервис который отдает данные для контроллера. В данном случае замоканные.

2022-08-23 19:04 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderExternalMapper.java
> +    OrderExternal mapOrderDtoToOrderExternal(OrderDto orderDto) {
где тесты?

2022-08-23 20:36 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/entity/OrderExternal.java
> +    @Type(type = "json")
прийняте рішення ліст продуктів із замовлення зберігати як raw data

2022-08-24 15:28 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderExternalMapper.java
> +@Component
added

2022-08-24 15:28 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/validator/MockOrderAddressValidator.java
> +@Component
changed

2022-08-24 15:29 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderExternalMapper.java
> +    OrderExternal mapOrderDtoToOrderExternal(OrderDto orderDto) {
add test

2022-08-25 05:25 UTC, Rooman requested changes
Намного лучше!

2022-08-25 05:25 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/dto/OrderDto.java
> +    private boolean isAddressValid;
https://stackoverflow.com/questions/5322648/for-a-boolean-field-what-is-the-naming-convention-for-its-getter-setter

2022-08-25 05:25 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/entity/OrderExternal.java
> +@Table(name = "orders_external")
grandedolce_orders

2022-08-25 05:25 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/entity/OrderExternal.java
> +    boolean isAddressValid;
private

2022-08-25 05:25 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/OrderController.java
> +        orderExternalService.save(inValidOrders);
повторяю свой предыдущий коммент. 
1 вызов сервиса должен быть в контроллере. 
Если вы мокаете, то мокайте на уровне сервиса. Чтобы во время замены мока никаких изменений в контроллере не было.

2022-08-26 13:05 UTC, belosh59 approved these changes

2022-08-26 13:19 UTC, BogdanParashchak approved these changes

2022-08-26 13:41 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/OrderValidationDto.java
> +    List<OrderDto> validOrders;
changed

2022-08-26 13:59 UTC, merged