Tests for DefaultCalculateRouteService class
BogdanParashchak/GoodsPartner pull request #111
Opened 2022-08-24 15:50 UTC by airavata-elephant

1. Create Util package in Service package
2. Moves methods from DefaultCalculateRouteService Class into GoogleApiHelper class:
- getRouteTotalDistance
- getRouteTotalTime
- addRoutPointDistantTime
3.Covered with Unit tests DefaultCalculateRouteService and GoogleApiHelper class

2022-08-25 17:06 UTC, belosh59 approved these changes

2022-08-25 17:55 UTC, 0ffffh requested changes

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/dto/CarDto.java
> +@ToString
зачем @ToString? не думаю что он тут нужен

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> +import java.util.Objects;
что-то лишнее

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> +    @ToString
@ToString

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/util/GoogleApiHelper.java
> +    @VisibleForTesting
метод public

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
>      @BeforeEach
@BeforeAll

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +    }
Строить такие обьекты очень сложно, можно читать из json файла. Попробуй ObjectMapper

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +        when(storeDto.getName()).thenReturn("Склад №1");
StoreService моковый, возвращает один склад с адресом, его можно тут использовать

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +        double actualTotalOrdersCount = routeService.getTotalOrders(routePoints);
int

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/util/GoogleApiHelperTest.java
> +        }
везде одинаково, вынеси в @Before создание DirectionsRoute
кстати тестовый rout лежит в файлике datasets/route/route.json

2022-08-25 17:55 UTC, 0ffffh commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +        Assertions.assertEquals(expectedRouteDto.toString(), actualRouteDto.toString());
так вот зачем был @toString  )
думаю что сравнивать два обьекта через toString не очень хорошая идея, можно сравнивать поля или посмотреть в сторону чего-то типа assertThat().isSameAs()

2022-08-25 17:57 UTC, belosh59 commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +        Assertions.assertEquals(expectedRouteDto.toString(), actualRouteDto.toString());
интересно, а я на это и не обратил внимание, спасибо Костя

2022-08-25 19:39 UTC, BogdanParashchak requested changes
do not use toString to compare objects

2022-08-25 21:41 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> +@Builder
why do you need Builder here?

2022-08-25 21:42 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/response/RoutesCalculation.java
> +    @ToString
same here

2022-08-25 21:42 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/response/RoutesCalculation.java
> +    @ToString
same here

2022-08-26 06:20 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/dto/CarDto.java
> +@ToString
видалено

2022-08-26 06:20 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> +import java.util.Objects;
видалено

2022-08-26 06:23 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> +@ToString
видалено

2022-08-26 06:23 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> +    @ToString
видалено

2022-08-26 06:30 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/util/GoogleApiHelper.java
> +    @VisibleForTesting
видалено

2022-08-26 06:50 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +        double actualTotalOrdersCount = routeService.getTotalOrders(routePoints);
виправлено

2022-08-26 07:26 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> +@Builder
using @Buider anotation  to create RoutePointDto object in DefaultCalculateRouteServiceTest class

2022-08-26 07:27 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/response/RoutesCalculation.java
> +    @ToString
removed

2022-08-26 07:28 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/response/RoutesCalculation.java
> +    @ToString
removed

2022-08-26 09:21 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +    }
Костя опрацюю окремою таскою

2022-08-26 09:22 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCalculateRouteServiceTest.java
> +        Assertions.assertEquals(expectedRouteDto.toString(), actualRouteDto.toString());
виправлено

2022-08-26 13:34 UTC, BogdanParashchak approved these changes

2022-08-29 08:57 UTC, Eugene7011 approved these changes

2022-08-29 08:59 UTC, Ishei5 approved these changes

2022-08-29 09:02 UTC, merged