76-sonarcloud-integration
BogdanParashchak/GoodsPartner pull request #113
Opened 2022-08-25 11:52 UTC by BogdanParashchak

2022-08-25 18:25 UTC, 0ffffh approved these changes

2022-08-25 21:39 UTC, belosh59 approved these changes

2022-08-26 04:02 UTC, Rooman requested changes
One flow for project please

2022-08-26 05:27 UTC, BogdanParashchak commented
Redundant GitHub Actions build removed

2022-08-26 05:51 UTC, Rooman approved these changes

2022-08-26 05:55 UTC, merged