Report, car load by grouped products
BogdanParashchak/GoodsPartner pull request #117
Opened 2022-08-28 19:20 UTC by Ishei5

logic for sheet generation moved to separate class;
added new sheet to report;
car name and licence plate moved to table header, this column are removed from template

2022-08-29 06:33 UTC, Eugene7011 approved these changes

2022-08-29 08:14 UTC, Ishei5 commented
Пример отчета:
[[2022-08-29_11-11-31]Завантаження_машин_на_2022-07-12.xlsx](https://github.com/BogdanParashchak/GoodsPartner/files/9442819/2022-08-29_11-11-31._._._2022-07-12.xlsx)

2022-08-29 09:03 UTC, NastyaBondarenko approved these changes

2022-08-29 09:15 UTC, BogdanParashchak requested changes

2022-08-29 09:15 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/report/CarLoadSheetGeneratorTest.java
> +        OrderDto order2 = OrderDto.builder()
please remove numbers in variable names

2022-08-29 11:32 UTC, belosh59 commented on goods-partner-backend/src/test/java/com/goodspartner/report/CarLoadSheetGeneratorTest.java
> +        OrderDto order2 = OrderDto.builder()
For my humble opinion in test it is acceptable.
Otherwise how do you propose to rename them? :)

2022-08-29 11:32 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +            String tittle = String.format("Звіт по завантаженню %s (%s) товарами", car.getName(), car.getLicencePlate());
Such things better to move to class constants - "Звіт по завантаженню %s (%s) товарами"

2022-08-29 11:33 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +            sheet.getRow(7).createCell(3).setCellValue("НА ОБРАНУ ДАТУ ЗАВАНТАЖЕНЬ НЕМАЄ");
Same here

2022-08-29 11:33 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +                currentRow.getCell(4).setCellValue("Загальна вага");
Same here

2022-08-29 11:33 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +            currentRow.getCell(4).setCellValue("Загальна вага всіх замовлень");
Same here

2022-08-29 11:33 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +        currentRow.getCell(4).setCellValue("Дата");
Same here

2022-08-29 11:34 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +            String tittle = String.format("Звіт по завантаженню %s (%s) товарами", car.getName(), car.getLicencePlate());
If such a constants are mainly reusable in various Report generators, it is better to create a separate ReportConstants class with those constants being listed

2022-08-29 11:39 UTC, belosh59 commented
@Ishei5 

А шо якщо ми назвемо поле сумарну строку - "Всього:" , де буде загальна кількість і загальна маса. 
Якщо це не важко переробити - думаю це маж сенс. Адже тоді людині не прийдеться самій це все перераховувати по кількості якщо певний артикул перечислений в багатьох замовленнях

<img width="944" alt="Screenshot 2022-08-29 at 12 36 52" src="https://user-images.githubusercontent.com/26186899/187192999-1eb1ec28-7131-48c6-b6a8-4b3361101a70.png">

2022-08-29 16:20 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +            String tittle = String.format("Звіт по завантаженню %s (%s) товарами", car.getName(), car.getLicencePlate());
> If such a constants are mainly reusable in various Report generators, it is better to create a separate ReportConstants class with those constants being listed

one common field, from my point of view it doesn't make sense to make a common class

2022-08-29 16:20 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +            String tittle = String.format("Звіт по завантаженню %s (%s) товарами", car.getName(), car.getLicencePlate());
> Such things better to move to class constants - "Звіт по завантаженню %s (%s) товарами"

Done

2022-08-29 16:20 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +            sheet.getRow(7).createCell(3).setCellValue("НА ОБРАНУ ДАТУ ЗАВАНТАЖЕНЬ НЕМАЄ");
Done

2022-08-29 16:20 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarLoadSheetGenerator.java
> +                currentRow.getCell(4).setCellValue("Загальна вага");
Done

2022-08-30 07:34 UTC, Ishei5 commented on goods-partner-backend/src/test/java/com/goodspartner/report/CarLoadSheetGeneratorTest.java
> +        OrderDto order2 = OrderDto.builder()
> please remove numbers in variable names

Done

2022-08-30 08:03 UTC, belosh59 approved these changes

2022-08-30 08:20 UTC, BogdanParashchak approved these changes

2022-08-30 08:21 UTC, merged