Cover DefaultCarLoadingService with test methods
BogdanParashchak/GoodsPartner pull request #135
Opened 2022-09-01 11:56 UTC by airavata-elephant

2022-09-02 07:56 UTC, BogdanParashchak requested changes
see comments

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    @DisplayName("Check loadCars Correctly Load Car")
"Check loadCars Correctly Load Car" - > "**_Test_** loadCars Correctly Load**_s_** Car
correct everywhere

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +                .routePoints(List.of(firstRoutePoints, secondRoutePoints))
a lot of times you use this List.of(firstRoutePoints, secondRoutePoints); logic in your test class
think about separate field

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +                .routePointDistantTime(55)
these fields have the same value as firstRoutePoints
make different

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultCarLoadingService.java
> +    RoutingModel configureRoutingModel(RoutingIndexManager manager, long[][] distanceMatrix, long[] demands, long[] vehicleCapacities, long[] vehicleCosts, int carsAmount) {
if you dont test this method then replace annotation and set correct access modifier

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/resources/datasets/route/distanceMatrix_for_loadCars.json
> +{
why do you create new file? we already have distanceMatrix.json

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        when(googleApiService.getDistanceMatrix(anyList())).thenReturn(routePointsMatrix);
as for me test works without this

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        long[][] distanceMatrix = defaultCarLoadingService.calculateDistanceMatrix(routePointsMatrix);
distanceMatrix -> distanceMatrixArray

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        when(googleApiService.getDistanceMatrix(anyList())).thenReturn(distanceMatrix);
unnessesary

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    void testLoadCars() throws IOException {
test another way
just verify mock googleApiService and carService were called in method

2022-09-02 07:56 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    @Test
no need to test this method because its logic contains methods which you test below

2022-09-02 16:04 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    void before() {
done

2022-09-02 16:04 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        DistanceMatrix distanceMatrix = new DistanceMatrix(origin, dest, distanceMatrixRows);
fixed

2022-09-02 16:20 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    @DisplayName("Check loadCars Correctly Load Car")
fixed

2022-09-02 16:29 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +                .routePoints(List.of(firstRoutePoints, secondRoutePoints))
good idea

2022-09-02 16:38 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultCarLoadingService.java
> +    RoutingModel configureRoutingModel(RoutingIndexManager manager, long[][] distanceMatrix, long[] demands, long[] vehicleCapacities, long[] vehicleCosts, int carsAmount) {
this method is not tested but is called in another method's test.

2022-09-02 16:39 UTC, airavata-elephant commented on goods-partner-backend/src/test/resources/datasets/route/distanceMatrix_for_loadCars.json
> +{
for a correct test, we needed to change the file data.

2022-09-02 16:41 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        when(googleApiService.getDistanceMatrix(anyList())).thenReturn(routePointsMatrix);
your right! fixed

2022-09-02 16:43 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        long[][] distanceMatrix = defaultCarLoadingService.calculateDistanceMatrix(routePointsMatrix);
+

2022-09-02 16:45 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        when(googleApiService.getDistanceMatrix(anyList())).thenReturn(distanceMatrix);
clear

2022-09-04 19:48 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    @MockBean
done

2022-09-04 19:48 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        CarLoadingService.CarRoutesDto actualCarRoutesDto = defaultCarLoadingService.getCarLoad(carDto, List.of(firstRoutePoints, secondRoutePoints));
done

2022-09-04 19:48 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +                defaultCarLoadingService.getCarLoadDtos(List.of(carDto), List.of(firstRoutePoints, secondRoutePoints), manager, routing);
done

2022-09-04 19:48 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        List<CarLoadingService.CarRoutesDto> actualCarRoutesDtos = defaultCarLoadingService.load(List.of(carDto), List.of(firstRoutePoints, secondRoutePoints), distanceMatrix);
done

2022-09-04 19:49 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        List<CarLoadingService.CarRoutesDto> actualCarRoutesDtos = defaultCarLoadingService.loadCars(storeDto, List.of(firstRoutePoints, secondRoutePoints));
done

2022-09-04 19:49 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    }
done

2022-09-04 19:49 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +                .id(null)
done

2022-09-04 19:49 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +                .id(null)
done

2022-09-04 19:50 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +                .routePointDistantTime(55)
done

2022-09-04 19:50 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +        long[][] distanceMatrix = defaultCarLoadingService.calculateDistanceMatrix(routePointsMatrix);
done

2022-09-04 19:50 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    void testLoadCars() throws IOException {
done

2022-09-04 19:51 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/service/impl/DefaultCarLoadingServiceTest.java
> +    @Test
clear

2022-09-05 18:03 UTC, BogdanParashchak approved these changes

2022-09-05 19:19 UTC, Eugene7011 approved these changes

2022-09-05 19:39 UTC, 0ffffh approved these changes

2022-09-06 06:28 UTC, merged