Create delivery entity
BogdanParashchak/GoodsPartner pull request #157
Opened 2022-09-13 17:59 UTC by Eugene7011

2022-09-13 21:31 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/response/RoutesCalculation.java
> +import com.goodspartner.entity.Delivery;
не используемый импорт

2022-09-13 21:32 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/DeliveryController.java
> +public class DeliveryController {
если будет возможность, сразу для swagger подобавлять описание через анотации

2022-09-13 21:44 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderMapper.java
> +import com.goodspartner.web.controller.response.RoutesCalculation;
не используемый импорт

2022-09-14 07:55 UTC, NastyaBondarenko requested changes

2022-09-14 07:55 UTC, NastyaBondarenko commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/DeliveryControllerITest.java
> +    void whenGetDeliveries_thenJsonReturned() throws Exception {
Судячи з назви тесту має вертатись json, але вертається тільки статус. Тут напевно або назва некоретна або json вказать треба.

2022-09-14 07:55 UTC, NastyaBondarenko commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/DeliveryControllerITest.java
> +    void whenGetDeliveryById_thenJsonReturned() throws Exception {
також не вертається json, тільки статус

2022-09-14 08:37 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/dto/DeliveryDto.java
> +@EqualsAndHashCode
нам тут треба EqualsAndHashCode?

2022-09-14 08:37 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/entity/DeliveryStatus.java
> +    APPROVED("APPROVED");
and COMPLETED

2022-09-14 08:42 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +    public DeliveryDto findByShippingDate(LocalDate date) {
by DeliveryDate

2022-09-14 08:54 UTC, Eugene7011 commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/DeliveryControllerITest.java
> +    void whenGetDeliveries_thenJsonReturned() throws Exception {
Да, сначала работал с json а потом поменял а название не исправил.
Поправлю

2022-09-14 08:55 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/entity/DeliveryStatus.java
> +    APPROVED("APPROVED");
Добавлю

2022-09-14 08:56 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +    public DeliveryDto findByShippingDate(LocalDate date) {
Изменю

2022-09-14 08:57 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderMapper.java
> +import com.goodspartner.web.controller.response.RoutesCalculation;
Убрал, спасибо

2022-09-14 08:57 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/DeliveryController.java
> +public class DeliveryController {
Это нужно тогда уточнить с тобой Илья

2022-09-14 12:23 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/OrderMapper.java
> +import com.goodspartner.web.controller.response.RoutesCalculation;
fixed

2022-09-14 12:28 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/DeliveryControllerITest.java
> +    void whenGetDeliveries_thenJsonReturned() throws Exception {
fixed

2022-09-14 12:28 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/DeliveryControllerITest.java
> +    void whenGetDeliveryById_thenJsonReturned() throws Exception {
fixed

2022-09-14 12:32 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/dto/DeliveryDto.java
> +@EqualsAndHashCode
@EqualsAndHashCode deleted

2022-09-14 12:34 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/entity/DeliveryStatus.java
> +    APPROVED("APPROVED");
fixed

2022-09-14 12:36 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +    public DeliveryDto findByShippingDate(LocalDate date) {
fixed

2022-09-14 12:36 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/entity/DeliveryStatus.java
> +
fixed

2022-09-14 12:37 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/mapper/ProductMapper.java
> +    List<Product> orderDtosToOrders(List<ProductDto> productDtos);
deletad as unnessesary

2022-09-14 12:39 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/DeliveryController.java
> +        deliveryService.update(id, delivery);
fixed

2022-09-14 17:31 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/DeliveryController.java
> +public class DeliveryController {
done

2022-09-15 06:16 UTC, NastyaBondarenko approved these changes

2022-09-15 07:12 UTC, BogdanParashchak approved these changes

2022-09-15 08:48 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/RouteService.java
> +
Why we need this method here?

2022-09-15 08:49 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +        updatedDelivery.setStatus(DeliveryStatus.APPROVED);
Why status is taken not from the DTO but is hard coded?

2022-09-15 08:50 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/entity/CarLoad.java
> +    @OneToMany(fetch = FetchType.LAZY)
OneToMany is Lazy by default

2022-09-15 08:51 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/entity/OrderExternal.java
> +import javax.persistence.*;
Please do not use asterics in import

2022-09-15 08:58 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +        return deliveryMapper.deliveryToDeliveryDto(deliveryRepository.findById(id)
minor.
deliveryRepository.findById(id)
.map(DeliveryMapper::deliveryToDeliveryDto)
.orElse(.....)

2022-09-15 08:58 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +        return deliveryMapper.deliveryToDeliveryDto(deliveryRepository.findByDeliveryDate(date));
Should be optional as well

2022-09-15 08:59 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/repository/DeliveryRepository.java
> +    Delivery findByDeliveryDate(LocalDate date);
Optional ?

2022-09-15 09:01 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +        updatedDelivery.setStatus(DeliveryStatus.APPROVED);
Why the status cannot be updated within the mapper?

2022-09-15 09:54 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/service/RouteService.java
> +
deleted

2022-09-15 09:55 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +        updatedDelivery.setStatus(DeliveryStatus.APPROVED);
fixed

2022-09-15 09:56 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/entity/CarLoad.java
> +    @OneToMany(fetch = FetchType.LAZY)
fixed here and in delivery entity

2022-09-15 09:58 UTC, Eugene7011 commented on goods-partner-backend/src/main/java/com/goodspartner/entity/OrderExternal.java
> +import javax.persistence.*;
+

2022-09-15 11:28 UTC, merged