Migrate all properties files to yml format
BogdanParashchak/GoodsPartner pull request #17
Opened 2022-07-15 11:41 UTC by Eugene7011

application.properties -> application.yml
application-dev.properties -> application-dev.yml
application-test.properties -> application-test.yml

2022-07-15 11:43 UTC, BogdanParashchak approved these changes
well done

2022-07-15 12:04 UTC, Rooman requested changes

2022-07-15 12:04 UTC, Rooman commented on src/main/resources/application-test.yml
> +    enabled: 'true'
кавычки?

2022-07-15 12:04 UTC, Rooman commented on src/main/resources/application.yml
> +    port: '${PORT:8080}'
кавычки?

2022-07-15 12:13 UTC, Eugene7011 commented on src/main/resources/application.yml
> +    port: '${PORT:8080}'
так конвертер делает и все работает. ща поправлю

2022-07-15 12:25 UTC, Eugene7011 commented on src/main/resources/application.yml
> +    port: '${PORT:8080}'
мне закрыть это пул риквест и создать новый с исправлениями? или этот можно поправить?

2022-07-15 17:52 UTC, Rooman requested changes

2022-07-15 17:52 UTC, Rooman commented on src/main/resources/application-dev.yml
> +    password: password
этот файл в гит игноре должен быть, его не нужно коммитить. Он у каждого свой

2022-07-15 17:52 UTC, Rooman commented on src/main/resources/application.yml
> +    mvc:
отсортируй, сначала с меньшей, потом с большей вложеностью

2022-07-18 08:08 UTC, Rooman approved these changes

2022-07-18 08:08 UTC, merged