149-track-driver-by-gps
BogdanParashchak/GoodsPartner pull request #204
Opened 2022-10-03 12:42 UTC by airavata-elephant

2022-10-03 13:55 UTC, belosh59 requested changes

2022-10-03 13:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/repository/CarLocationRepository.java
> +    void updateLocation(int id, Location location);
I would call it CarLocationCache

2022-10-03 13:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/repository/cashrepository/DefaultCarLocationRepository.java
> +        concurrentHashMap.replace(id, location);
https://stackoverflow.com/questions/35297537/difference-between-replace-and-put-for-hashmap 
Lets keep remove this method. Dont see much reason to support it.
We could go with save and get

2022-10-03 13:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultCarService.java
> +    private final CarLocationRepository carLocationRepository;
yes, CarLocationRepository name confuse assumes that there is real table entity - Location

2022-10-03 13:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultCarService.java
> +        validateCar(id);
I think this validateCar is useless for getting the location, since it there is no location for that car we just return nothing.
This is quite high performance drawback. I would get rid of this validation in both updateCarLocation and getCarLocation and assume that we keep what we send and dont care if it is linked to a existing car or not

2022-10-03 13:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultCarService.java
> +        }
Once you will remove updateLocation method yopu will not need to check this, you jsut always save whatever you got from frontend, do not sofisticate the solution

2022-10-03 13:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultCarService.java
> +    }
Just remove it, we dont want another DB interaction under this high freaquent operation

2022-10-03 13:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/CarController.java
> +    }
Test for this functionality required!!

2022-10-05 09:29 UTC, belosh59 approved these changes

2022-10-05 09:39 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/repository/cashrepository/DefaultCarLocationCache.java
> +package com.goodspartner.repository.cashrepository;
Cash repository ? Банкомат?

2022-10-05 09:42 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/dto/Location.java
> +    private double longitude;
Lets add LocalDateTime here, to know when we save this location

2022-10-05 09:58 UTC, BogdanParashchak requested changes
see comments

2022-10-05 09:58 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/repository/CarLocationCache.java
> +public interface CarLocationCache {
we don't need this interface, delete pls

2022-10-05 09:58 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/repository/cashrepository/DefaultCarLocationCache.java
> +package com.goodspartner.repository.cashrepository;
this is not repository
rename to CarLocationCache and move to com.goodspartner.cache

2022-10-05 10:25 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/repository/cashrepository/DefaultCarLocationCache.java
> +package com.goodspartner.repository.cashrepository;
fail, will fix

2022-10-05 10:26 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/dto/Location.java
> +    private double longitude;
ok! work with this

2022-10-05 10:26 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/repository/cashrepository/DefaultCarLocationCache.java
> +package com.goodspartner.repository.cashrepository;
ok

2022-10-05 10:35 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/repository/CarLocationCache.java
> +public interface CarLocationCache {
got it

2022-10-05 11:14 UTC, Eugene7011 commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +    void whenGetLocation_thenZeroLocationCoordinatesAndOkStatusReturned() throws Exception {
What does this test do? Please explain why zero returned

2022-10-05 11:15 UTC, Eugene7011 commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434);
You may initialize location Before all tests as you use it many times

2022-10-05 12:54 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434);
agree

2022-10-05 12:57 UTC, BogdanParashchak requested changes
see comments

2022-10-05 12:57 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434,DATE_TIME);
create one Location insatance per test class

2022-10-05 12:59 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434,DATE_TIME);
wrong formatting

2022-10-05 13:19 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +    void whenGetLocation_thenZeroLocationCoordinatesAndOkStatusReturned() throws Exception {
we have two options of answer from method "getLocation" :

2022-10-05 17:56 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +    void whenGetLocation_thenZeroLocationCoordinatesAndOkStatusReturned() throws Exception {
in CarLocationCache we have two scenario for method "getLocation":

2022-10-05 18:19 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434);
++

2022-10-05 18:24 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434,DATE_TIME);
its LocalDateTime format, so it's ok.
clarify bdlska what exectly wrong

2022-10-05 19:47 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434,DATE_TIME);
20.323434,DATE_TIME -> 20.323434, DATE_TIME

2022-10-05 20:00 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434,DATE_TIME);
ok

2022-10-05 20:02 UTC, airavata-elephant commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434,DATE_TIME);
claro 
ok

2022-10-05 20:02 UTC, belosh59 commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/CarControllerITest.java
> +        Location location = new Location(25.323434, 20.323434,DATE_TIME);
just simply use global file format
Ctrl + Alt + L for windows if I remember correctly

2022-10-05 20:36 UTC, belosh59 approved these changes

2022-10-05 20:41 UTC, BogdanParashchak approved these changes

2022-10-05 20:42 UTC, merged