69 recalculate route
BogdanParashchak/GoodsPartner pull request #216
Opened 2022-10-06 11:12 UTC by NastyaBondarenko

2022-10-07 10:47 UTC, airavata-elephant reviewed
check comment plz

2022-10-07 10:47 UTC, airavata-elephant commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteCalculationService.java
> +    Route mapToRoute(Route route, LinkedList<RoutePoint> routePoints) {
maybe a better name for the method is: "recalculateRoute" ?

2022-10-07 10:47 UTC, BogdanParashchak requested changes
see comments

2022-10-07 10:47 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteService.java
> +            throw new IllegalDeliveryStatusForOperation(savedDelivery, "get");
non-informative message
throw new IllegalDeliveryStatusForOperation(savedDelivery, "get"); -> throw new IllegalDeliveryStatusForOperation(savedDelivery, "recalculate route for APPROVED delivery ");

2022-10-07 10:47 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteService.java
> +            throw new IllegalRouteStatusForOperation(route, routeStatus.toString());
looks like mistake, see:
    public IllegalRouteStatusForOperation(Route route, String action) {
        super(String.format(ILLEGAL_STATUS_MESSAGE, action, route.getId(), route.getStatus()));
    }

2022-10-07 11:10 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/DeliveryController.java
> +    public void updateRecalculatedRoute(@PathVariable("id") UUID deliveryId, @PathVariable int routeId,
I would call it /reorder coz in the end we dont calculate the route we reordering it

2022-10-07 13:49 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteCalculationService.java
> +    Route mapToRoute(Route route, LinkedList<RoutePoint> routePoints) {
+

2022-10-07 13:49 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteService.java
> +        Route savedRoute = routeRepository.findById(routeId)
changed

2022-10-07 13:49 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteService.java
> +            Route updatedRoute = routeCalculationService.mapToRoute(savedRoute, routePoints);
changed

2022-10-07 13:49 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteService.java
> +            throw new IllegalDeliveryStatusForOperation(savedDelivery, "get");
changed

2022-10-07 13:50 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultRouteService.java
> +            throw new IllegalRouteStatusForOperation(route, routeStatus.toString());
changed

2022-10-07 13:50 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/DeliveryController.java
> +    public void updateRecalculatedRoute(@PathVariable("id") UUID deliveryId, @PathVariable int routeId,
changed

2022-10-07 23:38 UTC, belosh59 approved these changes

2022-10-07 23:49 UTC, belosh59 approved these changes

2022-10-08 06:32 UTC, BogdanParashchak approved these changes

2022-10-08 10:35 UTC, belosh59 requested changes
need time re-evaluation

2022-10-12 11:48 UTC, belosh59 approved these changes

2022-10-12 12:14 UTC, merged