Order service impl test to check quantity of quires to database
BogdanParashchak/GoodsPartner pull request #22
Opened 2022-07-20 17:41 UTC by Eugene7011

Add SqlTrackerTest (to assert quantity of queries to datasource), add TestConfiguration.
Add AbstractBaseTest  for all tests using TestContainer.
Refactoring (WebControllerTests).

2022-07-22 05:20 UTC, Rooman requested changes
@Ishei5 @Eugene7011 Понимаю что вы работали вместе над этим функционалом. Пройдитесь пожалуйста вместе по комментариям.

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/sqltracker/SqlTrackerTest.java
> +public class SqlTrackerTest extends AbstractBaseTest {
Это Тест Sql трекера? Или Ордер сервиса? 
Можем ли мы переименовать из Impl в DefaultOrderService. 
суффиксы у интеграционных тестов ITest плиз

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/sqltracker/SqlTrackerTest.java
> +@SpringBootTest(classes = TestConfiguration.class)
Ты наследуешся от класса в котором есть уже эта аннотация, так и должно быть что она дублируется?

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/sqltracker/SqlTrackerTest.java
> +@ActiveProfiles("test")
Может вынести активный профиль для тестов в класс родитель? 
Илиь вообще в yml файл?

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/AbstractBaseTest.java
> +public class AbstractBaseTest {
AbstractBaseITest

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/sqltracker/SqlTrackerTest.java
> +        assertSelectCount(12);
Это тест на DefaultOrderService. 
Делаем 3 разных теста для подсчета каждой из функциональностей

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/sqltracker/TestConfiguration.java
> +@ComponentScan(basePackages = {"com.goods.partner"})
Это точно нужно?

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/sqltracker/TestConfiguration.java
> +    Environment env;
Модификатор доступа

2022-07-22 05:20 UTC, Rooman commented on src/test/java/com/goods/partner/web/controller/OrdersEndpointIntegrationTest.java
> +                                        ",\"orderData\":" +
Вместо конкатенаций можно использовать синтаксис объявление строки в тройных кавычках. 
"""Привет 
          мир 
"""

2022-07-22 08:54 UTC, Eugene7011 commented on src/test/java/com/goods/partner/sqltracker/SqlTrackerTest.java
> +public class SqlTrackerTest extends AbstractBaseTest {
ок, переименую в DefaultOrderService

2022-07-22 08:55 UTC, Eugene7011 commented on src/test/java/com/goods/partner/sqltracker/SqlTrackerTest.java
> +@ActiveProfiles("test")
ок, в родитель

2022-07-22 08:56 UTC, Eugene7011 commented on src/test/java/com/goods/partner/sqltracker/TestConfiguration.java
> +@ComponentScan(basePackages = {"com.goods.partner"})
убрал @EnableAutoConfiguration. А без @ComponentScan не находит бин.

2022-07-22 09:39 UTC, Eugene7011 commented on src/test/java/com/goods/partner/sqltracker/SqlTrackerTest.java
> +@SpringBootTest(classes = TestConfiguration.class)
ок исправлю на @Import

2022-07-22 09:42 UTC, Eugene7011 reviewed
Rename OrderServiceImpl into DefaultOrderService
Rename SqlTrackerTest into DefaultOrderServiceITest
Add "I" to all integration tests
Splitted one test in DefaultOrderServiceITest into 3 tests for each method DefaultOrderService

2022-07-22 09:46 UTC, belosh59 approved these changes

2022-07-24 20:10 UTC, Ishei5 approved these changes

2022-07-25 13:34 UTC, belosh59 approved these changes

2022-07-25 13:34 UTC, merged