extend statistics with plots data
BogdanParashchak/GoodsPartner pull request #224
Opened 2022-10-09 01:11 UTC by belosh59

2022-10-09 10:57 UTC, Rooman approved these changes

2022-10-09 19:29 UTC, BogdanParashchak requested changes
see comments

2022-10-09 19:29 UTC, BogdanParashchak commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultStatisticsService.java
> +            dataForPeriodPerDay.put(dateFrom, routes != null ? routes : 0);
maybe:
  Integer **count** = mappingData.get(**date**);
  dataForPeriodPerDay.put(**date**, **count**!= null ? **count**: 0);
?

2022-10-09 21:19 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultStatisticsService.java
> +            dataForPeriodPerDay.put(dateFrom, routes != null ? routes : 0);
100%

2022-10-09 22:06 UTC, Rooman approved these changes

2022-10-10 06:43 UTC, Eugene7011 approved these changes

2022-10-11 08:12 UTC, merged