Added routPointDistantTime to RoutePointDto
BogdanParashchak/GoodsPartner pull request #28
Opened 2022-07-25 20:16 UTC by Ishei5

Renamed RouteServiceImpl.java -> DefaultRouteService.java

2022-07-25 21:14 UTC, Rooman requested changes

2022-07-25 21:14 UTC, Rooman commented on src/main/java/com/goods/partner/service/impl/DefaultRouteService.java
> +        AtomicInteger index = new AtomicInteger();
Этот код точно нельзя написать проще? без атомиков и переборов по индексу? 
Может быть обычным фором?

2022-07-25 21:14 UTC, Rooman commented on src/main/java/com/goods/partner/service/impl/DefaultRouteService.java
> +    private void addRoutPointDistantTime(List<RoutePointDto> routePoints, DirectionsRoute route) {
Где тест на новую функциональность. 
Юнит + исправление интеграционного.

2022-07-26 19:12 UTC, Ishei5 commented on src/main/java/com/goods/partner/service/impl/DefaultRouteService.java
> +        AtomicInteger index = new AtomicInteger();
Переделал с for. Оставил TODO на переделать потом с stream

2022-07-26 19:12 UTC, Ishei5 commented on src/main/java/com/goods/partner/service/impl/DefaultRouteService.java
> +    private void addRoutPointDistantTime(List<RoutePointDto> routePoints, DirectionsRoute route) {
Создал

2022-07-27 07:21 UTC, BogdanParashchak requested changes
1. Rename everywhere rout -> route
2. @VisibleForTesting for package-private method
3. Check for use of Duration instead of LocalTime

2022-07-27 07:21 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/dto/RoutePointDto.java
> +    private LocalTime routPointDistantTime;
points on the same route may be reached on different days (23:00 27/07 and 01:00 28/07)
then LocalTime is not correct
discuss for use of Java Duration instead

2022-07-28 08:27 UTC, BogdanParashchak approved these changes

2022-07-28 09:13 UTC, NastyaBondarenko approved these changes

2022-07-28 15:21 UTC, belosh59 commented on src/main/java/com/goods/partner/entity/RouteStatus.java
> +    private final String value;
А зачем нам Value тут если оно такое же как и сама енамка
Предлагаю убрать ее и сохранять в базе именно определения енамки

2022-07-28 19:37 UTC, Ishei5 commented on src/main/java/com/goods/partner/entity/RouteStatus.java
> +    private final String value;
Принято

2022-07-28 19:42 UTC, Rooman requested changes

2022-07-28 19:42 UTC, Rooman commented on src/main/java/com/goods/partner/entity/RouteStatus.java
> +public enum RouteStatus {
Я понимаю что многие пишут и так. 
Но я попрошу тебя сделать тут String name и оперировать им, а не строком представлением имени Энама

2022-07-28 20:46 UTC, Ishei5 commented on src/main/java/com/goods/partner/entity/RouteStatus.java
> +public enum RouteStatus {
Добавил стринг поле status

2022-07-29 09:15 UTC, Rooman approved these changes

2022-07-29 09:15 UTC, merged