Car service
BogdanParashchak/GoodsPartner pull request #29
Opened 2022-07-26 11:53 UTC by NastyaBondarenko

1. add car_service and tests.
2. add V4.0__Modify_cars_table.sql for new field (car`s status)

2022-07-26 12:15 UTC, BogdanParashchak requested changes
see comments
please answer each comment after fixing

2022-07-26 12:15 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenAddCar_thenCorrectJsonReturned() throws Exception {
_thenOkStatusReturned()

2022-07-26 12:15 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenAddCar_thenCorrectJsonReturned() throws Exception {
Add one more test to ckeck expected dataset where added car appears

2022-07-26 12:15 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenDeleteCar_thenEmptyJsonReturned() throws Exception {
_thenOkStatusReturned()

2022-07-26 12:15 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenDeleteCar_thenEmptyJsonReturned() throws Exception {
Add one more test to check expected dataset where car deleted

2022-07-26 12:15 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenUpdateCarStatus_thenCorrectJsonReturned() throws Exception {
Чому ти так називаєш метод :_thenCorrectJsonReturned(), але при цьому ти перевіряєш статус , а не джейсон?
виправ плз

2022-07-26 12:15 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenDeleteCar_thenEmptyJsonReturned() throws Exception {
check case for non-existing id

2022-07-26 12:15 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/web/controller/CarController.java
> +    public void createCar(@RequestBody Car car) {
addCar

2022-07-26 12:15 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/web/controller/CarController.java
> +        carService.createCar(car);
addCar

2022-07-26 12:15 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/service/impl/CarServiceImpl.java
> +        car.setStatus(car.getStatus());
car.setStatus(status);

2022-07-27 15:27 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenAddCar_thenCorrectJsonReturned() throws Exception {
changed

2022-07-27 15:27 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenAddCar_thenCorrectJsonReturned() throws Exception {
added

2022-07-27 15:28 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenDeleteCar_thenEmptyJsonReturned() throws Exception {
changed

2022-07-27 15:28 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenDeleteCar_thenEmptyJsonReturned() throws Exception {
added

2022-07-27 15:28 UTC, NastyaBondarenko commented on src/main/java/com/goods/partner/web/controller/CarController.java
> +    public void createCar(@RequestBody Car car) {
changed

2022-07-27 15:28 UTC, NastyaBondarenko commented on src/main/java/com/goods/partner/web/controller/CarController.java
> +        carService.createCar(car);
changed

2022-07-27 15:28 UTC, NastyaBondarenko commented on src/main/java/com/goods/partner/service/impl/CarServiceImpl.java
> +        car.setStatus(car.getStatus());
changed

2022-07-27 17:26 UTC, BogdanParashchak requested changes
see comments

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenAddCar_thenOkStatusReturned() throws Exception {
check case when add by existing (id=2) id

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml")
@DataSet("common/dataset_cars.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml", transactional = true)
@DataSet("common/dataset_cars.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml")
@DataSet("common/dataset_cars.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml")
@DataSet("common/dataset_cars.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @ExpectedDataSet(value = "common/dataset_add_car.yml")
@ExpectedDataSet("common/dataset_add_car.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @ExpectedDataSet(value = "common/dataset_update_car.yml")
@ExpectedDataSet("common/dataset_update_car.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @ExpectedDataSet(value = "common/dataset_delete_cars.yml")
@ExpectedDataSet("common/dataset_delete_cars.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @ExpectedDataSet(value = "common/dataset_cars.yml")
@ExpectedDataSet("common/dataset_cars.yml")

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    void whenUpdateCarStatus_thenOkStatusReturned() throws Exception {
check case when update by non existing id

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/resources/datasets/common/dataset_add_car.yml
> +    STATUS: "disable"
move to [src/test/resources/datasets/car]

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/resources/datasets/common/dataset_cars.yml
> +    STATUS: "disable"
move to [src/test/resources/datasets/car]

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/resources/datasets/common/dataset_delete_cars.yml
> +    STATUS: "disable"
move to [src/test/resources/datasets/car]

2022-07-27 17:26 UTC, BogdanParashchak commented on src/test/resources/datasets/common/dataset_update_car.yml
> +    STATUS: "disable"
move to [src/test/resources/datasets/car]

2022-07-27 17:26 UTC, BogdanParashchak commented on src/main/java/com/goods/partner/web/controller/CarController.java
> +}
status to be ENUM
when update check if status exists in enum

2022-07-29 07:44 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml")
changed

2022-07-29 07:44 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml", transactional = true)
changed

2022-07-29 07:44 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml")
changed

2022-07-29 07:44 UTC, NastyaBondarenko commented on src/test/java/com/goods/partner/web/controller/CarEndpointITest.java
> +    @DataSet(value = "common/dataset_cars.yml")
changed

2022-07-29 07:44 UTC, NastyaBondarenko commented on src/test/resources/datasets/common/dataset_add_car.yml
> +    STATUS: "disable"
moved

2022-07-29 07:44 UTC, NastyaBondarenko commented on src/test/resources/datasets/common/dataset_cars.yml
> +    STATUS: "disable"
moved

2022-07-29 07:44 UTC, NastyaBondarenko commented on src/test/resources/datasets/common/dataset_update_car.yml
> +    STATUS: "disable"
moved

2022-07-29 07:45 UTC, NastyaBondarenko commented on src/main/java/com/goods/partner/web/controller/CarController.java
> +}
added

2022-07-29 12:33 UTC, belosh59 commented on src/main/java/com/goods/partner/web/controller/CarController.java
> +    public void addCar(@RequestBody Car car) {
тут треба приймати DTO і конвертити його в модельку.
Контроллек не має оперувати моделями бази данних

2022-07-29 12:35 UTC, belosh59 commented on src/main/java/com/goods/partner/service/impl/CarServiceImpl.java
> +    private List<CarDto> carDtos;
давай просто приберемо це.
Це поле тут глобально доступне для всх потоків що будуть працювати із данними
Тому коли два потоки одночасно будуть відпрацьовувати логіку вони одночасно будуть модифікувати одну і ту саму колекцію.
Використовуй скоуп метода щоб бути ред сейф

2022-07-29 12:36 UTC, belosh59 commented on src/main/java/com/goods/partner/service/impl/CarServiceImpl.java
> +        carDtos = carMapper.mapCars(cars);
List<CarDto> carDtos = carMapper.mapCars(cars)

або взагалі лаконічно один метод
return carMapper.mapCars(carRepository.findAll());

2022-07-29 12:37 UTC, belosh59 commented on src/main/java/com/goods/partner/service/impl/CarServiceImpl.java
> +    @Transactional
тут можна використовувавти флаг Transactional(readOnly = true
)

2022-07-29 12:37 UTC, belosh59 commented on src/main/java/com/goods/partner/service/impl/CarServiceImpl.java
> +    @Transactional
думаю тут транзакція не потрібна адже ми не міняємо данні

2022-07-29 12:38 UTC, belosh59 commented on src/main/java/com/goods/partner/service/impl/CarServiceImpl.java
> +        carDtos.remove(carDtos.get(id));
це схоже на те що ти хотіла додати кеш для авто які у нас є. Але нам цього тут не потрібно, Просто круд сервіс

2022-08-01 11:51 UTC, Rooman approved these changes

2022-08-01 11:52 UTC, merged