added info adbout orders loaded in car at "/routes" endpoint
BogdanParashchak/GoodsPartner pull request #33
Opened 2022-08-03 21:27 UTC by 0ffffh

modified:   src/main/java/com/goods/partner/dto/CalculationRoutesDto.java
    -add: List CarLoadDetailsDto  for new tab
    
    new file:   src/main/java/com/goods/partner/dto/CarLoadDetailsDto.java
    - info about Car, orders, products
    
    new file:   src/main/java/com/goods/partner/dto/OrderInfoDto.java
    - order info : id, order number, list productInfo
    
    new file:   src/main/java/com/goods/partner/dto/ProductInfoDto.java
    -product info: name, amount
    
    new file:   src/main/java/com/goods/partner/mapper/CarDetailsMapper.java
    -map order -> orderInfo
    -set load order
    
    modified:   src/main/java/com/goods/partner/service/impl/DefaultOrderService.java
    -add CarLoadDetails list to calculationRoutes

JSON EXAMPLE: 

{
  "date": "2022-07-30",
  "routes": [
    {
      "routeId": 2,
      "status": "DRAFT",
      "totalWeight": 169.8,
      "totalPoints": 1,
      "totalOrders": 3,
      "distance": 152.06,
      "estimatedTime": "PT2H45M41S",
      "startTime": null,
      "finishTime": null,
      "spentTime": null,
      "storeName": "Склад №1",
      "storeAddress": "Фастів, вул. Широка, 15",
      "routePoints": [
        {
          "clientId": 2,
          "clientName": "ТОВ \"Кондитерська\"",
          "address": "м. Київ, вул. Глибочицька, 12Б, оф. 3",
          "addressTotalWeight": 169.8,
          "routePointDistantTime": "PT1H24M39S",
          "orders": [
            {
              "orderId": 11,
              "orderNumber": 6785
            },
            {
              "orderId": 12,
              "orderNumber": 40234
            },
            {
              "orderId": 13,
              "orderNumber": 987
            }
          ]
        }
      ],
      "car": {
        "id": 2,
        "name": "Mercedes Vito",
        "licencePlate": "AA 2222 CT",
        "driver": "Ivan Piddubny",
        "weightCapacity": 500,
        "cooler": false,
        "available": true,
        "loadSize": 169.8,
        "travelCost": 11
      }
    },
    {
      "routeId": 1,
      "status": "DRAFT",
      "totalWeight": 451.56,
      "totalPoints": 2,
      "totalOrders": 2,
      "distance": 154.28,
      "estimatedTime": "PT2H46M2S",
      "startTime": null,
      "finishTime": null,
      "spentTime": null,
      "storeName": "Склад №1",
      "storeAddress": "Фастів, вул. Широка, 15",
      "routePoints": [
        {
          "clientId": 1,
          "clientName": "ТОВ \"Пекарня\"",
          "address": "м. Київ, вул. Металістів, 8, оф. 4-24",
          "addressTotalWeight": 83.8,
          "routePointDistantTime": "PT1H22M37S",
          "orders": [
            {
              "orderId": 2,
              "orderNumber": 43532
            }
          ]
        },
        {
          "clientId": 3,
          "clientName": "ТОВ \"Хлібзавод\"",
          "address": "м. Київ, вул. Політехнічна, 1, оф. 65",
          "addressTotalWeight": 367.76,
          "routePointDistantTime": "PT4M45S",
          "orders": [
            {
              "orderId": 16,
              "orderNumber": 9656
            }
          ]
        }
      ],
      "car": {
        "id": 1,
        "name": "Mercedes Sprinter",
        "licencePlate": "AA 1111 CT",
        "driver": "Oleg Dudka",
        "weightCapacity": 500,
        "cooler": false,
        "available": true,
        "loadSize": 451.56,
        "travelCost": 5
      }
    }
  ],
  "carLoadDetails": [
    {
      "car": {
        "id": 2,
        "name": "Mercedes Vito",
        "licencePlate": "AA 2222 CT",
        "driver": "Ivan Piddubny",
        "weightCapacity": 500,
        "cooler": false,
        "available": true,
        "loadSize": 169.8,
        "travelCost": 11
      },
      "orders": [
        {
          "orderId": 13,
          "orderNumber": 987,
          "products": [
            {
              "productName": "6798 Фарба харчова червона",
              "amount": 3
            },
            {
              "productName": "576853 Масло екстра",
              "amount": 4
            }
          ]
        },
        {
          "orderId": 12,
          "orderNumber": 40234,
          "products": [
            {
              "productName": "6798 Фарба харчова червона",
              "amount": 3
            },
            {
              "productName": "576853 Масло екстра",
              "amount": 4
            }
          ]
        },
        {
          "orderId": 11,
          "orderNumber": 6785,
          "products": [
            {
              "productName": "3434 Паста шоколадна",
              "amount": 1
            },
            {
              "productName": "353 Стружка кокосова",
              "amount": 2
            }
          ]
        }
      ]
    },
    {
      "car": {
        "id": 1,
        "name": "Mercedes Sprinter",
        "licencePlate": "AA 1111 CT",
        "driver": "Oleg Dudka",
        "weightCapacity": 500,
        "cooler": false,
        "available": true,
        "loadSize": 451.56,
        "travelCost": 5
      },
      "orders": [
        {
          "orderId": 16,
          "orderNumber": 9656,
          "products": [
            {
              "productName": "8452 Масло 1й гатунок",
              "amount": 9
            },
            {
              "productName": "46643 Фарба харчова синя",
              "amount": 10
            }
          ]
        },
        {
          "orderId": 2,
          "orderNumber": 43532,
          "products": [
            {
              "productName": "6798 Фарба харчова червона",
              "amount": 3
            },
            {
              "productName": "576853 Масло екстра",
              "amount": 4
            }
          ]
        }
      ]
    }
  ]
}

2022-08-04 21:41 UTC, Rooman requested changes

2022-08-04 21:41 UTC, Rooman commented on src/main/java/com/goods/partner/dto/OrderInfoDto.java
> +    private int orderNumber;
Это стринг

2022-08-04 21:41 UTC, Rooman commented on src/test/java/com/goods/partner/web/controller/RoutesEndpointTest.java
> +                                              "amount": 1
А что такое эмаунт? как это будет выглядить на UI? 
Это кг? литры? тонны?

2022-08-05 12:08 UTC, Rooman approved these changes

2022-08-05 12:39 UTC, belosh59 approved these changes

2022-08-05 12:39 UTC, merged