Add report based on cars with orders
BogdanParashchak/GoodsPartner pull request #42
Opened 2022-08-10 12:48 UTC by NastyaBondarenko

2022-08-10 15:19 UTC, Eugene7011 approved these changes

2022-08-10 21:23 UTC, BogdanParashchak requested changes
build fails
for test mock service which uses google api key

2022-08-10 21:23 UTC, BogdanParashchak commented on goods-partner-backend/src/test/java/com/goodspartner/report/CarsReportGeneratorITest.java
> +        carsReportGenerator.generateReport(date, reportResultConsumer);
mock service which usee google api key

2022-08-11 10:59 UTC, NastyaBondarenko commented on goods-partner-backend/src/test/java/com/goodspartner/report/CarsReportGeneratorITest.java
> +        carsReportGenerator.generateReport(date, reportResultConsumer);
done

2022-08-11 11:02 UTC, BogdanParashchak approved these changes

2022-08-11 11:06 UTC, BogdanParashchak approved these changes

2022-08-11 11:34 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarsReportGenerator.java
> +            sheet.shiftRows(4, 5, (ordersQuantity - 1) * 2);
Magic numbers. 
Can we use some variables instead like
HEADER_INDEX = 4;

2022-08-11 14:02 UTC, NastyaBondarenko commented on goods-partner-backend/src/main/java/com/goodspartner/report/CarsReportGenerator.java
> +            sheet.shiftRows(4, 5, (ordersQuantity - 1) * 2);
added

2022-08-11 22:12 UTC, Rooman approved these changes

2022-08-12 09:43 UTC, Rooman approved these changes

2022-08-12 09:56 UTC, BogdanParashchak approved these changes

2022-08-12 09:56 UTC, merged