Unit tests for mappers
BogdanParashchak/GoodsPartner pull request #7
Opened 2022-07-05 21:56 UTC by 0ffffh

2022-07-05 23:07 UTC, Rooman requested changes

2022-07-05 23:07 UTC, Rooman commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +    private static Order mockOrder;
Зачем делать эти поля статическими?

2022-07-05 23:07 UTC, Rooman commented on src/test/java/com/goods/partner/mapper/StoreMapperTest.java
> +        verify(spyStoreMapper, times(1)).getStoreDto(storeProjection);
verify(spyStoreMapper).getStoreDto(storeProjection);

2022-07-05 23:07 UTC, Rooman commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +    private static Order mockOrder;
Аргумент - чтобы создавалось 1 раз - не аргумент. У нас нет проблем с производительностью в тестах. А если есть, покажи замеры до и после. 
Идея в том чтобы создать мок 1 раз на все тесты не всегда будет работать. Моки не всегда можно переиспользовать, и их нужно переинициализировать. Поэтому обычные поля + бефор ич.

2022-07-06 08:16 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +        assertEquals(50, addressOrderDto.getOrderTotalWeight(), 0.001);
do not calculate but just mention expected values (here and see next)

2022-07-06 08:19 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +
replace with 2 separate tests: 1st for verifing this logic return orders.stream().map(this::mapAddressOrder). collect(Collectors.toList()); 2nd for list of 3 elements (try to find method for list comparison)

2022-07-06 08:21 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +    }
eplace with 2 separate tests: 1st for verifing logic ; 2nd for list of 3 elements (try to find method for list comparison)

2022-07-06 08:36 UTC, BogdanParashchak commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +        List<AddressDto> addresses = clientDto.getAddresses();
move up

2022-07-06 08:56 UTC, TarasOrlovskyi requested changes

2022-07-06 08:56 UTC, TarasOrlovskyi commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +    static void setup() {
if you use @TestInstance(TestInstance.Lifecycle.PER_CLASS) over test class you can avoid 'static' fields and methods. So do that, in my view it will be better

2022-07-06 08:56 UTC, TarasOrlovskyi commented on src/test/java/com/goods/partner/mapper/ClientMapperTest.java
> +        assertEquals(clientDtoList.size(), 1);
swap parameters -> assertEquals(1, clientDtoList.size());

2022-07-06 08:56 UTC, TarasOrlovskyi commented on src/test/java/com/goods/partner/mapper/OrderMapperTest.java
> +        when(mockOrder.getCreatedDate()).thenReturn(LocalDate.of(2022, 01, 01));
change '01' to '1' -> LocalDate.of(2022, 1, 1)

2022-07-07 16:14 UTC, BogdanParashchak approved these changes

2022-07-07 16:22 UTC, merged