Modify:
BogdanParashchak/GoodsPartner pull request #8
Opened 2022-07-08 00:28 UTC by 0ffffh

1. application.properties:
- spring.profiles.active=dev
2. Procfile:
-Dspring.profiles.active=prod

Add:
1. application-dev.properties
2. application-prod.properties
3.  docker image with Postgres, Pgadmin4:
docker-compose.yml
servers.json
run -> docker-compose up --build -d

2022-07-08 02:53 UTC, Rooman requested changes

2022-07-08 02:53 UTC, Rooman commented on docker-compose.yml
> +services:
Какое отношение к задаче имеет докер компоуз и вообще докер?

2022-07-08 02:53 UTC, Rooman commented on servers.json
> +{
Аналогично. Это к чему?

2022-07-08 02:53 UTC, Rooman commented on src/main/resources/application-dev.properties
> +
Лишний пробел. 
dev.application.properties 
и этот файл у каждого свой его не нужно коммитить. Его нужно добавить в гит игнор

2022-07-08 02:53 UTC, Rooman commented on src/main/resources/application.properties
> +spring.flyway.baselineOnMigrate=true
Флайвэй тут причем?

2022-07-09 19:51 UTC, BogdanParashchak reviewed
Kostya, please answer Tolik`s comments.

2022-07-10 05:46 UTC, Rooman requested changes

2022-07-10 05:46 UTC, Rooman commented on src/main/resources/application-prod.properties
> +spring.datasource.url=${JDBC_DATABASE_URL}
prod.application.properties

2022-07-10 05:46 UTC, Rooman commented on src/main/resources/application.properties
> +spring.profiles.active=prod
Тоесть при обычном старте приложения у меня будет профиль прода? 
Это ошибка. 
Можем сделать чтобы по умолчанию был dev, если не указан какой то конкретный?

2022-07-10 06:40 UTC, 0ffffh commented on src/main/resources/application-prod.properties
> +spring.datasource.url=${JDBC_DATABASE_URL}
21.3 Profile specific properties

In addition to application.properties files, profile specific properties can also be defined using the naming convention application-{profile}.properties.

2022-07-10 06:40 UTC, 0ffffh commented on src/main/resources/application.properties
> +spring.profiles.active=prod
Ok

2022-07-10 17:24 UTC, BogdanParashchak commented on docker-compose.yml
> +services:
fixed

2022-07-10 17:24 UTC, BogdanParashchak commented on servers.json
> +{
fixed

2022-07-10 17:24 UTC, BogdanParashchak commented on src/main/resources/application-dev.properties
> +
done

2022-07-10 17:25 UTC, BogdanParashchak commented on src/main/resources/application.properties
> +spring.flyway.baselineOnMigrate=true
fixed

2022-07-10 17:37 UTC, BogdanParashchak commented on src/main/resources/application-prod.properties
> +spring.datasource.url=${JDBC_DATABASE_URL}
According to Spring default naming convention name of file to be  [application-prod.properties]
Otherwise additional configs are nessesary
https://docs.spring.io/spring-boot/docs/2.1.17.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-profile-specific-properties

2022-07-11 09:06 UTC, Rooman approved these changes

2022-07-11 09:06 UTC, merged