Add flyway
BogdanParashchak/GoodsPartner pull request #9
Opened 2022-07-08 00:29 UTC by 0ffffh

Add flyway maven dependency
Flyway migration V1.0 for current DB structure (V1/iteration#1)
Flyway migration V1.1 - Change data type for ID field(set autoincrement) in tables

2022-07-08 02:56 UTC, Rooman requested changes

2022-07-08 02:56 UTC, Rooman commented on src/main/resources/db/migration/V1.1__Modify_id_columns.sql
> +
Какой смысл разбивать на 2 миграции которые описывают две версии базы, если по факту у нас только одна версия сейчас?

2022-07-08 02:56 UTC, Rooman commented on src/main/resources/application.properties
> +spring.flyway.baselineOnMigrate = true
Зачем эта пропертя?

2022-07-08 06:37 UTC, BogdanParashchak reviewed
Look at Tolik comments

2022-07-10 17:54 UTC, BogdanParashchak approved these changes

2022-07-13 05:35 UTC, merged